FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

MAINTAINER zhousf

RUN apt-get update && \
    apt-get install -y \
        wget build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev \
        libgl1-mesa-glx libglib2.0-0 libsm6 libxrender1 libxext6 libreadline-dev libffi-dev  \
        libsqlite3-dev libbz2-dev liblzma-dev libgl1-mesa-glx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY Python-3.9.19.tgz .
RUN tar -xvf Python-3.9.19.tgz
RUN cd Python-3.9.19 && \
    ./configure --enable-optimizations && \
    make && \
    make install

RUN ln -s /usr/local/bin/python3 /usr/local/bin/python && \
    ln -s /usr/local/bin/pip3 /usr/local/bin/pip

COPY pip-24.2-py3-none-any.whl .
RUN python -m pip install --upgrade pip-24.2-py3-none-any.whl

COPY fastdeploy_python-1.0.7-cp39-cp39-manylinux1_x86_64.whl .
RUN pip fastdeploy_python-1.0.7-cp39-cp39-manylinux1_x86_64.whl --default-timeout=1000 -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com


